### ISSUE TITLE
[email sorting paging] sorting with special page number show wrong rows

### ISSUE THREAD

**Issue by hoelbing** [Xceptance/XCMailr#32]
Steps to reproduce:
- login and go to "My Email Addresses"
- add 6 emails (localpart name start with a to f)
- click "Display Count - 5 "

Result: Missing the email they start with d.. and the last email name start with f.
Expected: The 3 table row start with d and the email in last row start with e. If click "Display Count - ALL" then is the result of sorting correct.

**Comment by marcuskaufmann** [comment]
seems to be already fixed
