### ISSUE TITLE
Email Statistics: Forwarded Mails count is always 0

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XCMailr#40]
On the _Email Statistics_ page, the values shown in the _Forwarded Mails_ column of the _Sender Domains_ tables are always 0 although mails have been forwarded successfully. Please check whether the _Forwarded Mails_ series in the charts is affected as well.

**Comment by marcuskaufmann** [comment]
Should be fixed (with 0ece437097e68c5c362b9092527d903c93c5fb13) but isn't merged into master and thus not live yet.

**Comment by marcuskaufmann** [comment]
1f57dbb57a78da97a56acda038445d5cc17620ae fixed the issue
