### ISSUE TITLE
Email Statistics: chart time range varies strangely with every page load

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XCMailr#41]
The displayed time range of the _Last 24 Hours_ chart changes whenever I reload the page using F5, for example: 2pm-2pm -> 7pm-7pm -> 11am-11am.

**Comment by marcuskaufmann** [comment]
This is indeed a strange behavior. The only reason, I could imagine, is that this is a side effect of reusing objects to render to the UI. This has been changed (with b4ae68a3b48fb1c7f850ee1464d7ba9b6fee1cf1) and might be fixed already.

**Comment by marcuskaufmann** [comment]
I wasn't able to reproduce this bug locally but I still can see it on the production instance. Perhaps this a server side caching issue.

**Comment by marcuskaufmann** [comment]
Suddenly the graph could also be completely empty. Even the freemarker rendered output doesn't contain any data allthough their should be at least 24 zeros.

![firefox_2018-12-12_18-45-37](https://user-images.githubusercontent.com/16191117/49888380-27449180-fe3f-11e8-8d7d-229903b6f514.png)

**Comment by marcuskaufmann** [comment]
63e41df1e76f7532a01252dd08139f0776be372c
Added separate transaction

**Comment by marcuskaufmann** [comment]
It seems that the additional transaction fixed this issue.
