### ISSUE TITLE
Email Statistics: Separate axes for dropped and forwarded mails

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XCMailr#49]
Since the numbers of dropped and forwarded mails may diverge significantly, we should show them using separate chart axes.

**Comment by marcuskaufmann** [comment]
done with 75ee126dee98750b4ccd9cfadecde7aa619ab10b

**Comment by marcuskaufmann** [comment]
As discussed today we leave it to only one y-axis since one can choose data to be shown by clicking the graph legend. Thus y-axis rescales automatically to the selected data.
