### ISSUE TITLE
modified mail HTML content link 

### ISSUE THREAD

**Issue by rklehm-xc** [Xceptance/XCMailr#54]
XCMailr is used with Neodymium when checking HTML mail content sent out by the SUT. There is an a tag at the HTML with a modified @href value making this link not usable anymore for further checks.

The modified link content is also observed in the XCMailr web interface after loading the HTML content into the view.

expected: /INTERSHOP/web/WFS/IMT-DE-Site/de_DE/-/EUR/ViewCart-AddProductsBySkuAndQuantity?SKU=602030-8107-000&Quantity_602030-8107-000=1&Price_602030-8107-000=85.14

actual: /INTERSHOP/web/WFS/IMT-DE-Site/de_DE/-/EUR/ViewCart-AddProductsBySkuAndQuantity?SKU`2030-8107-000&Quantity_602030-8107-000=1&Price_602030-8107-000%EF%BF%BD.14

This sounds like an encoding issue somewhere in the XCMailr interface providing the HTML content and may be related to the = sign as the modification always starts where the origin has the equal sign.

**Comment by h-arlt** [comment]
Fixed in develop branch.
