### ISSUE TITLE
Layout of My Email Addresses page is broken when browserwidth is below 1200px

### ISSUE THREAD

**Issue by fpunktk** [Xceptance/XCMailr#6]
The layout of the German and English My Email Addresses page is broken with a browser window not wider than 1200px: 
![layout-emaillist-broken](https://f.cloud.github.com/assets/4948415/754010/5246509e-e57c-11e2-82a3-59d9029ea35d.png)

Perhaps the buttons can be displayed below each other to fix this. The layout should at least be okay with a width of 1024px.

**Comment by marcuskaufmann** [comment]
That was changed earlier and doesn't happen anymore.
