### ISSUE TITLE
Make domain check case-insensitive

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XCMailr#63]
XCMailr accepts emails targeted to certain domains only, for example "foo.com". So "john.doe@foo.com" will be processed and "john.doe@bar.com" will not, but logged as "relay denied" instead. However, if an email arrives with a recipient address of "JOHN.DOE@FOO.COM", the email will also not be processed which is probably not intended.

**Comment by h-arlt** [comment]
Adjusted code as follows:
 - lower-case list of configured mailbox domains (see property `mbox.dlist` in `application.conf`)
 - check domain of incoming mails case-insensitively
 - query for mailboxes by local and domain part case-insensitively
 - query for users by mail address case-insensitively

**Comment by h-arlt** [comment]
Superseded by #68 .

Reverted lower-casing of configured mailbox domains.
