### ISSUE TITLE
Link in Password reset email points to localhost

### ISSUE THREAD

**Issue by MarcusGuenter** [Xceptance/XCMailr#98]
Steps:

- Request password reset link 
- Check Email

The password reset email contains a link to localhost instead of to the system.
![image](https://github.com/Xceptance/XCMailr/assets/48118486/ef8d8403-e429-47a2-bfbe-4db6dfc0144f)

**Comment by h-arlt** [comment]
Issue is caused by improper configuration of our XCMailr instance and unrelated to XCMailr as it works as desired/configured.
